[versions]
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
markdown = "0.7.3"
jfree = "5.0.7"
kaml = "0.104.0"
npm-bootstrap = "5.3.8"
npm-sass = "1.94.2"
npm-minicss = "2.9.4"
npm-sharebuttons = "1.9.0"
npm-highlightjs = "11.11.1"
npm-highlightjsCopyPlugin = "1.0.6"
npm-loader-yaml = "0.8.1"
npm-loader-css = "7.1.2"
npm-loader-sass = "16.0.6"
npm-giscus = "3.1.0"

[libraries]
markdown-jvm = { module = "org.jetbrains:markdown-jvm", version.ref = "markdown" }
kaml-jvm = { module = "com.charleskorn.kaml:kaml-jvm", version.ref = "kaml" }
jfree-svg = { module = "org.jfree:org.jfree.svg", version.ref = "jfree" }

[libraries.kotlinx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
version.ref = "kotlinx-serialization"

[libraries.kotlinx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "kotlinx-datetime"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
